version: "2"
checks:
  method-lines:
    config:
      threshold: 30
plugins:
  eslint:
    enabled: true
    channel: "eslint-4"
    config: 
      config: .eslintrc.json
    checks:
      # due to eslint version differences the indent rules reported
      # on codecov are different from those on latest
      indent:
        enabled: false  
exclude_patterns:
  - ".github/"
  - "config/"
  - "dist/"
  - "doc/"
  - "src/lib/"
  - "test/"
  - "types/"
  - "utl/"
  - "**/node_modules/"
  - "**/*.d.ts"
  - "src/parse/*parser.js"
  - "src/render/**/*.template.js"
  - "webpack.config.js"